### ISSUE TITLE
Implement sender class to be compatible with receiver class

### ISSUE THREAD

**Issue by hazelweeling** [Extensible-Clinical-Imaging-QC-Tool/ECIQC#41]
Relevant Requirements from GE:
- [ ]  It shall be possible to specify multiple DICOM repositories as data transfer targets
- [ ] If an outbound transfer is not possible, data shall be retained, and the user notified.

**Comment by hazelweeling** [comment]
Implement storescu and echoscu. 
Links:
https://www.systutorials.com/docs/linux/man/1-storescu/
https://support.dcmtk.org/docs/echoscu.html

**Comment by jkrol8** [comment]
https://support.dcmtk.org/docs/classDcmStorageSCU.html

**Comment by jkrol8** [comment]
From today's discussion @hazelweeling 
- [ ] Change class inheritance to DcmStorageSCU
- [ ] Implement a constructor for Sender, taking in following arguments: AETitle, peerPort, peerHostName, peerAETitle
- [ ] Implement handling of C-Store Request
- [ ] Implement a function sendDICOM (or something like this) that takes in a DicomDataset (or a list of Datasets) and sends it using C-STORE
