### ISSUE TITLE
Create a minimal pipeline for GE testing

### ISSUE THREAD

**Issue by hazelweeling** [Extensible-Clinical-Imaging-QC-Tool/ECIQC#46]
- Generate a simple program to run whole pipeline for GE testing.
- Create a README and document process.

**Comment by hazelweeling** [comment]
- [ ] Instantiate Receiver Class and run simple C-ECHO and C-STORE requests. (Mona) @newc6536  
- [ ] Instantiate Sender Class and run simple C-ECHO and C-STORE requests. (Hazel)

**Comment by hazelweeling** [comment]
To implement sender and receiver class into conductor class.

**Comment by hazelweeling** [comment]
Basic functionality of conductor class is working. Able to receive and send C-ECHO AND C-STORE requests.
Next steps:
- [ ] Tidy up conductor class. Currently using structs to implement test SCU and own receiver class to implement test SCP. 
- [ ] Validate the same DICOM file/dataset that has been received by the Receiver class can be transferred by the Sender class.
- [ ] Add more functionalities to the command line tool.

**Comment by hazelweeling** [comment]
Preliminary Instructions to run CLI tool. 
- Tool that implements the receiver and sender class through the conductor class. 
- After compiling the project, run the code "./build/exe/qctool"  from the command line. 
- For help in configuring the parameters, run the code "./build/exe/qctool --help" from the command line.

**Comment by hazelweeling** [comment]
- [ ] : Include Parser class within Conductor class.

**Comment by martinjrobins** [comment]
need a thread safe queue, see here: https://codereview.stackexchange.com/questions/267847/thread-safe-message-queue

**Comment by pistacja96** [comment]
i46 branch with the minimal pipeline implementation has now been merged to `main`. Link to the merged branch [here](https://github.com/Extensible-Clinical-Imaging-QC-Tool/ECIQC/commit/4e41e5250d9f14fd7baae22d37a62a8e4851f2d2).
