### ISSUE TITLE
Further Understanding of presentation context

### ISSUE THREAD

**Issue by weiym97** [Extensible-Clinical-Imaging-QC-Tool/ECIQC#72]
We have added many presentation contexts in the sender and receiver. It ensures our files can travel smoothly between different entities. However, there's still one file that failed (DICOM_Image/testtext.dcm). We need to investigate the reason, and try to fix it.

Ideally, we would better understand how presentation context works, and maybe have a more flexible version of adding presentation context function.

**Comment by alexisiddiqui** [comment]
presentation done
