### ISSUE TITLE
Adding the logging file for each image.

### ISSUE THREAD

**Issue by weiym97** [Extensible-Clinical-Imaging-QC-Tool/ECIQC#73]
Logging has been added, but the present logging is a bit chaotic. There are two aims for this issue:

(1) create a separate logging file for each image;
(2) enable the user to specify the general log filename using the command line.

**Comment by pistacja96** [comment]
Also change the print outs throughout the codebase  to logging messages.

**Comment by pistacja96** [comment]
We have a new issue #86 which reflects better the scope of the logging. For now, we will archive the per-image logging functionality and focus on setting up a general logger.
